server:
  port: 8080
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #url: jdbc:dm://10.105.73.121:12345/EMSHIS
      url: jdbc:dm://192.168.1.210/EMSHIS
      #url: jdbc:dm://192.168.:12345/EMSHIS
      username: IPSM_DBA
      password: IPSM_DBA
      driver-class-name: dm.jdbc.driver.DmDriver
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

mybatis:
  basepackage: com.wlkj.ipsm.realtime.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

#分页控件配置
pagehelper:
  helper-dialect: dm
  reasonable: true
  support-methods-arguments: true
  params: countSql

#日志输出
logging:
  level:
    com.epri.fx.server: debug

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

auth:
  user:
    token-header: Authorization

